### ISSUE TITLE
Penamaan title HTML document

### ISSUE THREAD

**Issue by FarrelAD** [ngekost-aja/Ngekost-Aja#17]
Seluruh file HTML yang dibuat ditulis dengan isi tag title sebagai berikut: `<title>Ngekost Aja!</title>`

**Comment by I4annet** [comment]
ok lah kalau begitu kalau semisalnya ada halaman login dikasih begini kah `<title> Login - Ngekost Aja!</title>` apakah seperti ini ?

**Comment by FarrelAD** [comment]
Tetap seperti ini`<title>Ngekost Aja!</title>`

**Comment by I4annet** [comment]
> Tetap seperti ini`<title>Ngekost Aja!</title>`
